### ISSUE TITLE
apple T2  ramdisk file

### ISSUE THREAD

**Issue by DuyFXx** [genhack/ft_my#1]
Hi, I saw your comment on the Badcaps forum about bypassing the T2 chip. I can provide a ramdisk image with an SSH connection and mount filesystem for FREE, just need a method to bypass the activation lock. May I contact you?

**Comment by genhack** [comment]
Hy duyFxx, I don't need thanks. About your question there is some ways, You can patch the Activation Framework (the magic), the old clone an activate cert and plist from a random mac(apple fix this way on the new ibridge). GL
